CC := cc
CFILES := ft_hexdump.c
OFILES := ft_hexdump.o
CFLAGS := -Wall -Wextra -Werror
NAME := ft_hexdump

all: $(NAME)

clean:
	rm -f $(OFILES)

fclean: clean
	rm -f $(NAME)

.PHONY:  all clean fclean