CC := cc
CFILES := ft_tail.c tail2.c
OFILES := ft_tail.o tail2.o
HEADER := ft.h
CFLAGS := -Wall -Wextra -Werror -Iincludes
NAME := ft_tail

all: $(NAME)

clean:
	rm -f $(OFILES)

fclean: clean
	rm -f $(NAME)

.PHONY:  all clean fclean