CC := cc
CFILES := ft_display_file.c
OFILES := ft_display_file.o
CFLAGS := -Wall -Wextra -Werror
NAME := ft_display_file

all: $(NAME)

clean:
	rm -f $(OFILES)

fclean: clean
	rm -f $(NAME)

.PHONY:  all clean fclean
